### ISSUE TITLE
add me to list

### ISSUE THREAD

**Issue by 0xameer** [Hexstream/common-lispers.hexstreamsoft.com#11]
My init.org is controlled by common-lisp ( more often than not)
Portal : sdf.org/~sameers
I may take up maintenance of hacrm in future and am seeking work in the same lines , in market or community.

**Comment by Hexstream** [comment]
Have you reviewed the [minimum requirements for inclusion](https://common-lispers.hexstreamsoft.com/policies/#minimum-requirements) and other policies?

Do you have open-source Common Lisp contributions somewhere?

**Comment by Hexstream** [comment]
Please reopen if or when you meet the minimum requirements for inclusion.
