### ISSUE TITLE
Assenters and Objectors (CANCELLED)

### ISSUE THREAD

**Issue by Hexstream** [Hexstream/common-lispers.hexstreamsoft.com#12]
Out of [practicality](https://common-lispers.hexstreamsoft.com/policies/#tenets_practicality) concerns I have not contacted any of the first 100 Common Lispers list members, and out of [consistency](https://common-lispers.hexstreamsoft.com/policies/#tenets_consistency) concerns I don't intend to contact anyone else before adding them, either.

Nobody has received, nor will receive, any type of notification as a direct result of them getting added to the list. Indeed that is part of the point of me not contacting anyone before adding them to the list, as that could certainly be seen as "spamming" or otherwise undesirable.

But I guess it would be useful to know who is happy, unhappy or neutral about being represented in the list.

**edit: This has been [cancelled](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/12#issuecomment-484748928). This post is now historical.**

**~~So, it's now possible for list members to formally register as an Assenter, Objector or Ambivalent, depending on if they are explicitly happy, unhappy or neutral about being represented in the list, respectively. Simply let me know by replying to this issue and I will add you in the corresponding slot.~~ To avoid any unfortunate misunderstandings, this "Assenters and Objectors" list is entirely opt-in and I will **not** interpret any offhand comments anywhere as an implicit request to be added to it.**

My initial idea was to represent this information directly in the list, but on second thought, that's probably way too political for the list which is explicitly apolitical (and I'm about to add Apoliticality as an explicit tenet). By registering here, you consent to your registration status being eventually represented in some way in the Common Lispers list. **You can change your registration status at any time.** (You can also revert to "Unknown" status, which is neither Assenter nor Objector nor Ambivalent.)

# Assenters
*None yet.*

# Objectors
*None yet.*

# Ambivalents
*None yet.*

**Comment by Hexstream** [comment]
It's easy to find all [invalid removal requests](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues?utf8=%E2%9C%93&q=label%3A%22Invalid+removal+request%22).

**Comment by lispm** [comment]
> Out of practicality concerns I have not contacted any of the first 100 Common Lispers list members, and out of consistency concerns I don't intend to contact anyone else before adding them, either.

This is a gross privacy violation.

**Comment by lispm** [comment]
> But I guess it would be useful to know who is happy, unhappy or neutral about being represented in the list.

I'm unhappy.

**Comment by Hexstream** [comment]
> This is a gross privacy violation.

I don't understand how so. Please explain why you think that is so. I remind you again that the Common Lispers list aggregates public information only. Public facts that people have willingly publicly disclosed about themselves. This has already been extensively explained to you. The [policies](https://common-lispers.hexstreamsoft.com/policies/) (that you have repeatedly refused to read) also mention this.

Surely it wouldn't have been better if I had actively spammed all these people...

**Comment by Hexstream** [comment]
> I'm unhappy and I'm don't want to be listed at all. Remove all data from me.

Your request has already been repeatedly received and "processed", which of course does not include removing you from the list, as that would be contrary to the [policies](https://common-lispers.hexstreamsoft.com/policies/), which I again encourage you to read.

This thread is to change one's registration status as Assenter/Objector/Ambivalent, not for general discussion. You might tempt me to completely abandon this "registration" concept, in which case not even a partial remedy would be offered to objectors...

**Comment by lispm** [comment]
This is all bullshit.

I want to be removed from your list, from your website. Delete any data you store about me.

**Comment by Hexstream** [comment]
I have repeatedly acknowledged and responded to your requests and repeatedly [told you](https://common-lispers.hexstreamsoft.com/policies/#removal) why I cannot and will not remove you from the site.

I feel your pain, but I cannot destroy or gravely endanger my infrastructure just to please you.

**Comment by lispm** [comment]
> why I cannot and will not remove you from the site.

You lie. You can remove me from your site. Just do it.

> I feel your pain, but I cannot destroy or gravely endanger my infrastructure just to please you.

That's all bullshit. Delete me.

**Comment by Hexstream** [comment]
> You lie. You can remove me from your site. Just do it.

I never lie. There are tons of things that I could *technically* do that I still cannot *responsibly* do.

> That's all bullshit. Delete me. I never wanted to be listed on any of your websites. I never gave any permission to use my data and I DEMAND TO BE NOT LISTED.

I would appreciate if you could stop rehashing the same old shit ad eternam, it doesn't help anything (especially not your rhetorical position) and it's a waste of time for us both and anyone who comes by.

**Comment by lispm** [comment]
I don't care about your bullshit, take me off of your site.

**Comment by lispm** [comment]
> waste of time

Remove me from this site. Don't waste time.

**Comment by Hexstream** [comment]
> I don't care about your bullshit, take me off of your site.

You're rehashing the same old shit again. I don't know where you got the idea that repeatedly rehashing the same old shit would get you anywhere. You know what they say:

"**The definition of insanity is doing the same thing over and over and expecting different results.**"

**Comment by lispm** [comment]
Let me list 'public' information about you. Let's see, there are nude pictures of on twitter, your porn pictures on twitter, your pony masturbation pictures.

**Comment by Hexstream** [comment]
There are no "nude" pictures of me on twitter, dear.

(Shirtless is not "nude".)

**Comment by lispm** [comment]
Delist me. I want to be as far as possible from this shit.

**Comment by Hexstream** [comment]
Actively ensnaring yourself in this needless quarrel of your own making is the opposite of "staying as far as possible"...

**Comment by lispm** [comment]
Delist me. I want to be as far as possible from this shit.

**Comment by Hexstream** [comment]
> Let me list 'public' information about you. Let's see, there are nude pictures of you on twitter, your porn pictures on twitter, your pony masturbation pictures, your rants against members of the Lisp community, your conspiracy theories, ... would I put it on a website? Sure not.

Dear, I have virtually no regrets about anything I've been doing online, and if someone were to document it, it would still be much less annoying than the endless onslaught of senseless slandering I've been a target of and that you have at times [taken part in](https://twitter.com/HexstreamSoft/status/1118571528852000769).

**Comment by lispm** [comment]
Delist me. I want to be as far as possible from this shit.

**Comment by lispm** [comment]
Now you can update your website. My website lispm.de is gone. It's no longer on the Internet.

**Comment by Hexstream** [comment]
That's cute, I applaud you.

While I would eventually reflect the supposed "demise" of your site in the list, note that you are still quite within the [minimum requirements for inclusion](https://common-lispers.hexstreamsoft.com/policies/#minimum-requirements), and so you still legitimately have your place in the list.

**Comment by Hexstream** [comment]
Rainer Joswig (lispm) shat here then [deleted all his messages in shame](https://web.archive.org/web/20190418013246/https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/12), I'm not sure what the hell kind of a strategy that is...

I actually captured this page twice, **one with all of Rainer Joswig's messages** and the other one that I linked to above, but for some reason, **I can't access the former from the [captures page](https://web.archive.org/web/*/https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/12)**, even though it clearly says that there are "2 captures", "2 snapshots", that it's been "Saved 2 times".

**Please let me know if you find a way to access this capture!**

**Comment by Hexstream** [comment]
Based on experience with the first 2 (observed but not registered) objectors in particular, this concept of "registration of assenters and objectors" doesn't look too useful after all, so I'm cancelling it for now.

**Comment by Hexstream** [comment]
[I'm happy to announce that a much more potent remedy is now offered to objectors!](https://twitter.com/HexstreamSoft/status/1119328334452789251)
