### ISSUE TITLE
Jean-Philippe Paradis fails to remove users as requested. Can't recommend this website.

### ISSUE THREAD

**Issue by lispm** [Hexstream/common-lispers.hexstreamsoft.com#13]
Be very careful about using this website and anything related to the owner 'Jean-Philippe Paradis' alias 'Hexstream'.

**Comment by lispm** [comment]
Don't be fooled by his policies. He does not care.

**Comment by Hexstream** [comment]
The [policies](https://common-lispers.hexstreamsoft.com/policies/#removal) very extensively explain why I can't simply remove objectors.

Nobody has even tried to challenge these extensive rationales as of yet.

**Comment by Hexstream** [comment]
I'm not sure what it is you claim I do not care about.
I care about the Common Lisp community, for instance.
I don't believe you do.

**Comment by lispm** [comment]
I don't want anything other than NOT appearing with my personal data in any of your websites.

Don't take me hostage with your crap.

**Comment by Hexstream** [comment]
See note in bold [here](https://common-lispers.hexstreamsoft.com/policies/#removal_dignity).

You will not be able to intelligibly debate about the [policies](https://common-lispers.hexstreamsoft.com/policies/) until you read them and understand them.

**Comment by lispm** [comment]
Don't take me hostage with your childish 'policy' crap. Just delete me from your fucking website.

**Comment by Hexstream** [comment]
I'm not sure how this translates into a "hostage" situation.

**Comment by lispm** [comment]
Just stop coming up with more crap. Just delete me.

**Comment by Hexstream** [comment]
Civil society is built on policies. Is civil society childish, then?

**Comment by lispm** [comment]
Delete me.

**Comment by Hexstream** [comment]
I think you haven't faced enough refusals in your life.
That may be why you behave like an entitled child.

**Comment by lispm** [comment]
Stop taking me hostage with your crap, delete me.

**Comment by Hexstream** [comment]
You have yet to explain how this translates into a "hostage" situation.

**Comment by lispm** [comment]
I don't want to explain anything. Just remove me.

**Comment by lispm** [comment]
I don't care for what you are available. I don't want to be on your website. Delete me.

**Comment by Hexstream** [comment]
Per the [policies](https://common-lispers.hexstreamsoft.com/policies/) which you don't care about but are still in force, [I cannot simply remove objectors](https://common-lispers.hexstreamsoft.com/policies/#removal).

As previously stated, you may [register as an Objector](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/12) if you wish, and this is the only remedy I have to offer you.

Thank you, and please consider having a good night's sleep before engaging further.

**Comment by lispm** [comment]
Look, I don't want to register. I want to be removed.

Don't take me hostage with all your imaginary crap.

**Comment by Hexstream** [comment]
This is the third time I have to ask how this translates into a "hostage" situation.

**Comment by lispm** [comment]
No, you repeatedly fail to delete my data. Instead you want me to register. I don't want to read your crap, I don't want to register for your crap. I want to be deleted.

**Comment by lispm** [comment]
delete me from your website

**Comment by Hexstream** [comment]
I hope one day you'll look back on your current behavior and laugh.

**Comment by lispm** [comment]
delete me from your website.

**Comment by Hexstream** [comment]
May you grasp this opportunity for great personal growth.

**Comment by lispm** [comment]
I have opened a privacy violation issue at Github. You will hear from them.

**Comment by Hexstream** [comment]
This is within expectations. I am looking forward to it.

**Comment by lispm** [comment]
delete my data instead.

**Comment by Hexstream** [comment]
I was looking forward to a healthy public debate, yet all you have to offer is empty repeated demands (and a threat).

I guess my [policies](https://common-lispers.hexstreamsoft.com/policies/) are more ironclad than even I realized.

**Comment by lispm** [comment]
delete me, don't take me hostage with your 'debate' crap.

**Comment by Hexstream** [comment]
This is the fourth time I have to ask how this translates into a "hostage" situation.

**Comment by lispm** [comment]
Delete me. Dont't waste my time with your crap.

**Comment by Hexstream** [comment]
You are wasting your own time, and mine also.

**Comment by lispm** [comment]
Delete me, now.

**Comment by Hexstream** [comment]
Rainer Joswig (lispm) [shat here](https://web.archive.org/web/20190415182329/https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/13) then [deleted all his messages in shame](https://web.archive.org/web/20190418031928/https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/13), I'm not sure what the hell kind of a strategy that is...
