### ISSUE TITLE
Add ebrasca to list

### ISSUE THREAD

**Issue by ebrasca** [Hexstream/common-lispers.hexstreamsoft.com#17]
Hi can you add ebrasca to the list?

**Comment by Hexstream** [comment]
Probably, but more information would help. See #16 and #15 for example, and consider reviewing the [Common Lispers list](https://common-lispers.hexstreamsoft.com/) and [its policies](https://common-lispers.hexstreamsoft.com/policies/) for inspiration.

**Comment by ebrasca** [comment]
Name: Bruno Cichon
Nick: ebrasca
IRC Nick: ebrasca
github: https://github.com/ebrasca
notabug.org: https://notabug.org/ebrasca
CL Projects: Mezzano , and others

**Comment by Hexstream** [comment]
Wonderful! Thank you. You will be added soon.

**Comment by Hexstream** [comment]
Thank you for your add request!

[Your entry is live!](https://common-lispers.hexstreamsoft.com/#Bruno_Cichon)

I hope this is to your satisfaction.
