### ISSUE TITLE
Please add me ,

### ISSUE THREAD

**Issue by kmcorbett** [Hexstream/common-lispers.hexstreamsoft.com#18]
Name: Keith M Corbett
Nick: kmc
IRC Nick: 
github: https://github.com/kmcorbett
notabug.org:
CL Projects: None at present

**Comment by Hexstream** [comment]
Thank you for your interest in the Common Lispers list.

Have you reviewed the [policies](https://common-lispers.hexstreamsoft.com/policies/)?
I'll be happy to add you if or when you meet the [minimum requirements for inclusion](https://common-lispers.hexstreamsoft.com/policies/#minimum-requirements).

**Comment by Hexstream** [comment]
Please reopen and append to this issue if or when you meet the aforementioned minimum requirements for inclusion.
