### ISSUE TITLE
Add me if you wish

### ISSUE THREAD

**Issue by Slids** [Hexstream/common-lispers.hexstreamsoft.com#20]
Name: Jonathan Godbout
Nick: jgodbout
IRC jgodbout
github: https://github.com/slids
notabug.org: noppers
CL Projects: 
Maintainer of https://github.com/google/lisp-koans
Maintainer of https://github.com/qitab
Blog: https://experimentalprogramming.wordpress.com/

**Comment by Slids** [comment]
By noppers I mean I don't have one, I just realized thats not obvious..

**Comment by Hexstream** [comment]
Thank you for your add request!

[Your entry is live!](https://common-lispers.hexstreamsoft.com/#Jon_Godbout)

I hope this is to your satisfaction.
