### ISSUE TITLE
Can you add me?

### ISSUE THREAD

**Issue by mdbergmann** [Hexstream/common-lispers.hexstreamsoft.com#21]
Name: Manfred Bergmann
github: https://github.com/mdbergmann
CL Projects: https://github.com/mdbergmann/cl-gserver
Blog: http://retro-style.software-by-mabe.com/blog

I've got an additional question.
What is the list for? How is the list used?

**Comment by Hexstream** [comment]
Thank you for your add request!

[Your entry is live!](https://common-lispers.hexstreamsoft.com/#Manfred_Bergmann)

I hope this is to your satisfaction.

----------

> What is the list for? How is the list used?

The Common Lispers list serves the Common Lisp community across various use-cases. You may find [its policies](https://common-lispers.hexstreamsoft.com/policies/) enlightening.
