### ISSUE TITLE
Remove me from this list

### ISSUE THREAD

**Issue by phoe** [Hexstream/common-lispers.hexstreamsoft.com#24]
Please remove me and all of my personally identifiable information from this list.

I am not interested in partial resolutions of any kind, please simply remove me altogether.

**Comment by Hexstream** [comment]
A [partial resolution](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/23#issuecomment-701440055) is the only kind of resolution I am planning to offer at this time, sorry.

**edit:** I assume you have already read [the relevant part of the policies](https://common-lispers.hexstreamsoft.com/policies/#removal).

**Comment by phoe** [comment]
No. I am not interested in partial resolutions of any kind, please remove me altogether.

**Comment by Hexstream** [comment]
I would strongly recommend against [trying to pull a Rainer Joswig](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues?q=is%3Aissue+is%3Aopen+label%3A%22Rainer+Joswig+%28lispm%29+was+here.+%F0%9F%98%B1%22), although I do not believe you would be capable of this (as in, you are far too sane).

**Comment by phoe** [comment]
I am not interested in pulling anyone or anything. Please remove me from this list.

**Comment by Hexstream** [comment]
See #25.

**Comment by phoe** [comment]
I don't want a partial removal and I don't care about your personal policies. Please remove me altogether from this list.

**Comment by Hexstream** [comment]
[Please consult a mental health professional.](https://twitter.com/HexstreamSoft/status/1331127527977463809)

**Comment by Hexstream** [comment]
I see that [you already are](https://github.com/quicklisp/quicklisp-projects/issues/1941#issuecomment-733829726). I commend you, and wish you best of luck in treating your issues.
