### ISSUE TITLE
Add me please

### ISSUE THREAD

**Issue by MistressRemilia** [Hexstream/common-lispers.hexstreamsoft.com#26]
Name: Remilia Scarlet
Nick: MistressRemilia
Mastodon: https://mastodon.sdf.org/@MistressRemilia
CL Projects: all listed here https://alexa.partition36.com/programming/

**Comment by Hexstream** [comment]
**Amazing!!** Thank you for your add request, it had been a while since I had received one of these!

I will process this tomorrow.

**edit:** Forgot to ask, what do you want as your two highlights?

Review the [Common Lispers list](https://common-lispers.hexstreamsoft.com/) for inspiration.

**Comment by Hexstream** [comment]
Forgot to ask, what do you want as your two highlights?

Review the [Common Lispers list](https://common-lispers.hexstreamsoft.com/) for inspiration.

**Comment by MistressRemilia** [comment]
cl-meltysynth: https://chiselapp.com/user/MistressRemilia/repository/CL-MeltySynth/
midi123: https://chiselapp.com/user/MistressRemilia/repository/midi123/

Am I able to open a request to change these later?  Within reason, of course.

**Comment by Hexstream** [comment]
Yes, actually this is pretty much the only type of customization supported at this time, heh...

**Comment by Hexstream** [comment]
[Your entry is live!](https://common-lispers.hexstreamsoft.com/#Remilia_Scarlet)

I hope this is to your satisfaction.
