### ISSUE TITLE
Please add me to list

### ISSUE THREAD

**Issue by mark-watson** [Hexstream/common-lispers.hexstreamsoft.com#6]
Mark Watson

Code for my Loving Common Lisp book: https://github.com/mark-watson/loving-common-lisp

Web site: https://markwatson.com

Commercial products: ExperOps5 for Macintosh and Xerox 1108 Lisp Machine

**Comment by Hexstream** [comment]
Hello, thank you very much for your add request!

Unfortunately, this has been a very busy day, and my brothers are visiting, hence I'll only have time to get to this tomorrow.

Thank you for your patience!

**Comment by ryukinix** [comment]
Wow, that person has interesting stuff. I would like to see him on the list.

**Comment by Hexstream** [comment]
I intend to add everyone who meets the [minimum requirements for inclusion](https://common-lispers.hexstreamsoft.com/policies/#minimum-requirements).

**Comment by Hexstream** [comment]
Sorry, there has been [a slight change of plans](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/pull/3#issuecomment-478370073), so I won't be able to process your add request today, after all. I apologize.

**Comment by Hexstream** [comment]
Alright! I was finally able to process your add request today.

[Your entry is live!](https://common-lispers.hexstreamsoft.com/#Mark_Watson)

I hope this is to your satisfaction.
