### ISSUE TITLE
Please add me to the list :)

### ISSUE THREAD

**Issue by duncan-bayne** [Hexstream/common-lispers.hexstreamsoft.com#8]
Duncan Bayne

Common Lisp Buildpack for Heroku: https://gitlab.com/duncan-bayne/heroku-buildpack-common-lisp (on the shoulders of giants; see [credits](https://gitlab.com/duncan-bayne/heroku-buildpack-common-lisp#credits)).

Web site: https://duncan.bayne.id.au/

**Comment by Hexstream** [comment]
Alright! I was finally able to process your add request today.

[Your entry is live!](https://common-lispers.hexstreamsoft.com/#Duncan_Bayne)

I hope this is to your satisfaction.

**Comment by duncan-bayne** [comment]
Great, thank you :)

**Comment by Hexstream** [comment]
Thank you for being part of the first batch of add requests!
